a = input("digite algo ")
print('O tipo primitivo desse valor é ,',  type(a))
print('so tem espaços? ', a.isspace())
print('é um numero?', a.isnumeric())
print('é alfabetico?', a.isalpha())
print('é alfanumerico? ', a.isalnum())
print('é maisculo?', a.isupper())
print('é minusculo?', a.islower())
print("esta maiuscula e minuscula?// capitalizado ", a.istitle())

